modLoader="javafml"
loaderVersion="[46,)"

license="All Rights Reserved"
issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"
showAsResourcePack=false

[[mods]]
modId="randomstuff"
version="1.0.0.0"
displayName="Random Stuff"
updateJSONURL="https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json"
displayURL="https://minecraftforge.net"
logoFile="logo.png"
credits="Did I do it?"
authors="gachiBASS"
description='''
  Adds random stuff. Nuff said.
  '''
displayTest="MATCH_VERSION"